# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 549)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.portButton = QtWidgets.QPushButton(self.layoutWidget)
        self.portButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.portButton.setObjectName("portButton")
        self.verticalLayout_2.addWidget(self.portButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settingsLabel = QtWidgets.QLabel(self.layoutWidget)
        self.settingsLabel.setObjectName("settingsLabel")
        self.horizontalLayout.addWidget(self.settingsLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.versionLabel = QtWidgets.QLabel(self.layoutWidget)
        self.versionLabel.setText("")
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout.addWidget(self.versionLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonsListBox = QtWidgets.QListWidget(self.layoutWidget)
        self.buttonsListBox.setMinimumSize(QtCore.QSize(300, 0))
        self.buttonsListBox.setObjectName("buttonsListBox")
        self.verticalLayout_2.addWidget(self.buttonsListBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.clearButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.clearButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_5.addWidget(self.clearButton)
        self.comActivityEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.comActivityEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.comActivityEdit.setObjectName("comActivityEdit")
        self.verticalLayout_5.addWidget(self.comActivityEdit)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menuBar)
        self.action_Save_com_port = QtWidgets.QAction(MainWindow)
        self.action_Save_com_port.setObjectName("action_Save_com_port")
        self.actionSave_Actions = QtWidgets.QAction(MainWindow)
        self.actionSave_Actions.setObjectName("actionSave_Actions")
        self.menu_File.addAction(self.action_Save_com_port)
        self.menu_File.addAction(self.actionSave_Actions)
        self.menuBar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fast Serial"))
        self.portButton.setText(_translate("MainWindow", "Setup COM port"))
        self.settingsLabel.setText(_translate("MainWindow", "Settings"))
        self.clearButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Run selected tests.</p></body></html>"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_Save_com_port.setText(_translate("MainWindow", "&Save Com Port"))
        self.actionSave_Actions.setText(_translate("MainWindow", "Save &Actions"))
