# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'action_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(423, 256)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_3.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout_3.addWidget(self.nameEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.crRadio = QtWidgets.QRadioButton(self.groupBox)
        self.crRadio.setObjectName("crRadio")
        self.verticalLayout.addWidget(self.crRadio)
        self.lfRadio = QtWidgets.QRadioButton(self.groupBox)
        self.lfRadio.setObjectName("lfRadio")
        self.verticalLayout.addWidget(self.lfRadio)
        self.bothRadio = QtWidgets.QRadioButton(self.groupBox)
        self.bothRadio.setChecked(True)
        self.bothRadio.setObjectName("bothRadio")
        self.verticalLayout.addWidget(self.bothRadio)
        self.noneRadio = QtWidgets.QRadioButton(self.groupBox)
        self.noneRadio.setObjectName("noneRadio")
        self.verticalLayout.addWidget(self.noneRadio)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.actionLabel = QtWidgets.QLabel(Dialog)
        self.actionLabel.setObjectName("actionLabel")
        self.verticalLayout_2.addWidget(self.actionLabel)
        self.actionEdit = QtWidgets.QTextEdit(Dialog)
        self.actionEdit.setObjectName("actionEdit")
        self.verticalLayout_2.addWidget(self.actionEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nameLabel.setText(_translate("Dialog", "Name:"))
        self.groupBox.setTitle(_translate("Dialog", "End Of Line Options:"))
        self.crRadio.setText(_translate("Dialog", "Carriage Return"))
        self.lfRadio.setText(_translate("Dialog", "Linefeed"))
        self.bothRadio.setText(_translate("Dialog", "Both"))
        self.noneRadio.setText(_translate("Dialog", "None"))
        self.actionLabel.setText(_translate("Dialog", "Text to send:"))
