# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterDialog(object):
    def setupUi(self, FilterDialog):
        FilterDialog.setObjectName("FilterDialog")
        FilterDialog.resize(526, 166)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FilterDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nameLabel = QtWidgets.QLabel(FilterDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_3.addWidget(self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(FilterDialog)
        self.nameEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.nameEdit.setObjectName("nameEdit")
        self.verticalLayout_3.addWidget(self.nameEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.filterLabel = QtWidgets.QLabel(FilterDialog)
        self.filterLabel.setObjectName("filterLabel")
        self.verticalLayout_2.addWidget(self.filterLabel)
        self.filterEdit = QtWidgets.QTextEdit(FilterDialog)
        self.filterEdit.setObjectName("filterEdit")
        self.verticalLayout_2.addWidget(self.filterEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(FilterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(FilterDialog)
        self.buttonBox.accepted.connect(FilterDialog.accept)
        self.buttonBox.rejected.connect(FilterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FilterDialog)

    def retranslateUi(self, FilterDialog):
        _translate = QtCore.QCoreApplication.translate
        FilterDialog.setWindowTitle(_translate("FilterDialog", "Dialog"))
        self.nameLabel.setText(_translate("FilterDialog", "Name:"))
        self.filterLabel.setText(_translate("FilterDialog", "Regular Expression - show matching text"))
