# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(170, 33)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editButton = QtWidgets.QPushButton(Form)
        self.editButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.nameLabel = QtWidgets.QLabel(Form)
        self.nameLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout.addWidget(self.nameLabel)
        self.actionLabel = QtWidgets.QLabel(Form)
        self.actionLabel.setMaximumSize(QtCore.QSize(0, 0))
        self.actionLabel.setObjectName("actionLabel")
        self.horizontalLayout.addWidget(self.actionLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.editButton.setText(_translate("Form", "Edit"))
        self.nameLabel.setText(_translate("Form", "Action"))
        self.actionLabel.setText(_translate("Form", "Action"))
