# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetupDialog(object):
    def setupUi(self, SetupDialog):
        SetupDialog.setObjectName("SetupDialog")
        SetupDialog.resize(227, 135)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SetupDialog.sizePolicy().hasHeightForWidth())
        SetupDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(SetupDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.startButton = QtWidgets.QPushButton(SetupDialog)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 2, 2, 1, 1)
        self.comportLabel = QtWidgets.QLabel(SetupDialog)
        self.comportLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.comportLabel.setObjectName("comportLabel")
        self.gridLayout.addWidget(self.comportLabel, 0, 0, 1, 1)
        self.baudCBox = QtWidgets.QComboBox(SetupDialog)
        self.baudCBox.setObjectName("baudCBox")
        self.gridLayout.addWidget(self.baudCBox, 1, 1, 1, 1)
        self.baudLabel = QtWidgets.QLabel(SetupDialog)
        self.baudLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.baudLabel.setObjectName("baudLabel")
        self.gridLayout.addWidget(self.baudLabel, 1, 0, 1, 1)
        self.comportCBox = QtWidgets.QComboBox(SetupDialog)
        self.comportCBox.setObjectName("comportCBox")
        self.gridLayout.addWidget(self.comportCBox, 0, 1, 1, 1)
        self.comportRefreshButton = QtWidgets.QPushButton(SetupDialog)
        self.comportRefreshButton.setObjectName("comportRefreshButton")
        self.gridLayout.addWidget(self.comportRefreshButton, 0, 2, 1, 1)

        self.retranslateUi(SetupDialog)
        QtCore.QMetaObject.connectSlotsByName(SetupDialog)

    def retranslateUi(self, SetupDialog):
        _translate = QtCore.QCoreApplication.translate
        SetupDialog.setWindowTitle(_translate("SetupDialog", "Dialog"))
        self.startButton.setText(_translate("SetupDialog", "Start"))
        self.comportLabel.setText(_translate("SetupDialog", "COM port"))
        self.baudLabel.setText(_translate("SetupDialog", "BAUD"))
        self.comportRefreshButton.setText(_translate("SetupDialog", "refresh"))
